### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by TheGamer1002** [NoaHimesaka1873/t2fand#1]
What it says.
```
$ sudo t2fand
T2 Fan Daemon is not running, but PID file exists, indicating a previous crash. Removing PID file...
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/t2fand", line 232, in <module>
    fan.enable_manual()
  File "/usr/bin/t2fand", line 37, in enable_manual
    Path(self.path + "_manual").write_text("1")
  File "/usr/lib/python3.11/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
OSError: [Errno 5] Input/output error
```
```
sudo dmesg | tail -n 25
[ 2829.579770] bce-vhci: Not implemented: wait for pending output requests
[ 2829.580749] bce-vhci: Not implemented: wait for pending output requests
[ 2829.581656] bce-vhci: Not implemented: wait for pending output requests
[ 2829.582782] bce-vhci: Not implemented: wait for pending output requests
[ 2831.019318] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[ 2874.588589] bce-vhci: Not implemented: wait for pending output requests
[ 2874.589419] bce-vhci: Not implemented: wait for pending output requests
[ 2874.589977] bce-vhci: Not implemented: wait for pending output requests
[ 2874.590538] bce-vhci: Not implemented: wait for pending output requests
[ 2919.601155] bce-vhci: Not implemented: wait for pending output requests
[ 2919.602497] bce-vhci: Not implemented: wait for pending output requests
[ 2919.603691] bce-vhci: Not implemented: wait for pending output requests
[ 2919.604715] bce-vhci: Not implemented: wait for pending output requests
[ 2932.686073] applesmc: key=773 fan=1 temp=28 index=27 acc=0 lux=0 kbd=0
[ 2932.686153] applesmc APP0001:00: hwmon_device_register() is deprecated. Please convert the driver to use hwmon_device_register_with_info().
[ 2949.235974] applesmc APP0001:00: write_smc_mmio(11 F0Md) failed: 135
[ 2949.236299] applesmc APP0001:00: write_smc_mmio(11 F0Md) failed: 135
[ 2964.400491] bce-vhci: Not implemented: wait for pending output requests
[ 2964.401300] bce-vhci: Not implemented: wait for pending output requests
[ 2964.401943] bce-vhci: Not implemented: wait for pending output requests
[ 2964.402528] bce-vhci: Not implemented: wait for pending output requests
[ 3009.413268] bce-vhci: Not implemented: wait for pending output requests
[ 3009.414549] bce-vhci: Not implemented: wait for pending output requests
[ 3009.415851] bce-vhci: Not implemented: wait for pending output requests
[ 3009.417180] bce-vhci: Not implemented: wait for pending output requests
```
```
Linux (me)-MacBook-Air 6.3.1-arch1-1-t2 #1 SMP PREEMPT_DYNAMIC Sun, 14 May 2023 06:46:31 +0000 x86_64 GNU/Linux
```
EndeavourOS using the T2 build from t2linux.org on a late-2018 MacBook Air. My laptop's getting kinda hot.

**Comment by NoaHimesaka1873** [comment]
Seems like applesmc error. WONTFIX since not related to t2fand directly. Please file issue to kernel project or #general at our Discord.
